### ISSUE TITLE
Import failing

### ISSUE THREAD

**Issue by VooqadAfterburner** [PiloeGAO/Maya-ArmorPaintLiveLink#1]
Probably something I'm doing wrong, but I'm seeing the following when trying to import in to Maya 2020.2:

![Capture](https://user-images.githubusercontent.com/70160112/91251306-088d4800-e753-11ea-9678-b0228712c698.PNG)

Eventually I tried copying **pyArmorPaint_livelink.py** and the **icon** folder in to every **scripts** folder I could find in **username\documents\maya** but always received the same error.

**Comment by PiloeGAO** [comment]
Hello,

Thank you for using this plugin.

The error isn't related to the install but from the actual command.

Can you try to split the command into two lines?
Like that:
```
import pyArmorPaint_livelink
pyArmorPaint_livelink.show()
```

This may work now.

**Comment by VooqadAfterburner** [comment]
I'm seeing this now:

![image](https://user-images.githubusercontent.com/70160112/91981963-791f0080-ed21-11ea-8963-7d8d475e6549.png)

**Comment by PiloeGAO** [comment]
Hello,
Can you send me a demo scene?
I couldn't reproduce the error for now but with a demo scene I may get it.
Thank you

**Comment by VooqadAfterburner** [comment]
See attached

[cabinet.zip](https://github.com/PiloeGAO/Maya-ArmorPaintLiveLink/files/5179369/cabinet.zip)

**Comment by PiloeGAO** [comment]
I have tried and your file work correctly on my computer.
I see on your screenshot an empty space in directory name between "Armorpaint" and "0.8dev".
This can be an issue. Can you try to remove it please?
Can you send me a screenshot of the content of this directory?

**Comment by VooqadAfterburner** [comment]
```
import pyArmorPaint_livelink
pyArmorPaint_livelink.show()
ArmorPaint Live Link 1.0.0          https://github.com/PiloeGAO          leonumerique@gmail.com

ArmorPaint directory as been changed: D:/ArmorPaint0.8dev
Please re-open the UIpyArmorPaint_livelink.show()
ArmorPaint Live Link 1.0.0          https://github.com/PiloeGAO          leonumerique@gmail.com
select -r draw ;
File not exist
# Warning: Plug-in, "objExport.mll", is already loaded.  Skipped. # 
// Error: line 1: No object matches name: .color // 
// Error: line 1: No object matches name: .ambientColor // 
// Error: line 1: No object matches name: .normalCamera // 
# Error: WindowsError: file C:\Program Files\Autodesk\Maya2020\bin\python27.zip\subprocess.py line 958: 2 # 
```

**Comment by VooqadAfterburner** [comment]
My Armor Paint executable was called **krom.exe** because I compiled it myself.
Renaming it to **armorpaint.exe** resolved the problem.
Thanks for your assistance.
