### ISSUE TITLE
smooth preview

### ISSUE THREAD

**Issue by VooqadAfterburner** [PiloeGAO/Maya-ArmorPaintLiveLink#3]
thanks for making this, it's awesome; but it's not importing meshes into AP with smooth preview.
dunno if this is an AP or LL issue, but for reason reason the only way i've ever been able to import a smoothed preview is via fbx instead of obj.
problem this causes is it messes up certain bakes.

Maya 2020.3
ArmorPaint 0.8

**Comment by PiloeGAO** [comment]
Hello @VooqadAfterburner ,
Thanks for using the plugin.
I'm currently working on the version 2.0.
I add this request to my todo list.

**Comment by VooqadAfterburner** [comment]
Awesome
